package com.example.battlesimulator.model.enums;

/**
 * Battle abilities supported by the simulator.
 * Some newer or form-based abilities are implemented in simplified form.
 */
public enum Ability {
    NONE("None", "No ability."),

    BLAZE("Blaze", "Boosts Fire moves in a pinch."),
    TORRENT("Torrent", "Boosts Water moves in a pinch."),
    OVERGROW("Overgrow", "Boosts Grass moves in a pinch."),
    SWARM("Swarm", "Boosts Bug moves in a pinch."),
    TECHNICIAN("Technician", "Boosts weaker moves."),
    ADAPTABILITY("Adaptability", "Improves STAB."),
    SHEER_FORCE("Sheer Force", "Boosts moves with secondary effects."),
    TOUGH_CLAWS("Tough Claws", "Boosts contact moves."),
    IRON_FIST("Iron Fist", "Boosts punching moves."),
    MEGA_LAUNCHER("Mega Launcher", "Boosts pulse and aura moves."),
    STRONG_JAW("Strong Jaw", "Boosts biting moves."),
    RECKLESS("Reckless", "Boosts recoil moves."),
    SNIPER("Sniper", "Powers up critical hits."),
    SUPER_LUCK("Super Luck", "Raises critical-hit ratio."),
    HUSTLE("Hustle", "Boosts physical power but lowers accuracy."),
    HUGE_POWER("Huge Power", "Doubles Attack."),
    PURE_POWER("Pure Power", "Doubles Attack."),
    GUTS("Guts", "Boosts Attack when statused."),
    QUICK_FEET("Quick Feet", "Boosts Speed when statused."),
    MARVEL_SCALE("Marvel Scale", "Boosts Defense when statused."),
    SOLAR_POWER("Solar Power", "Boosts Sp. Atk in sun, loses HP."),
    SWIFT_SWIM("Swift Swim", "Boosts Speed in rain."),
    CHLOROPHYLL("Chlorophyll", "Boosts Speed in sun."),
    SAND_RUSH("Sand Rush", "Boosts Speed in sand."),
    SLUSH_RUSH("Slush Rush", "Boosts Speed in hail."),
    SAND_FORCE("Sand Force", "Boosts Rock, Ground and Steel moves in sand."),
    SAND_VEIL("Sand Veil", "Boosts evasion in sand."),
    SNOW_CLOAK("Snow Cloak", "Boosts evasion in hail."),

    INTIMIDATE("Intimidate", "Lowers the foe's Attack on entry."),
    LEVITATE("Levitate", "Immune to Ground-type moves."),
    WATER_ABSORB("Water Absorb", "Heals when hit by Water-type moves."),
    VOLT_ABSORB("Volt Absorb", "Heals when hit by Electric-type moves."),
    FLASH_FIRE("Flash Fire", "Absorbs Fire-type moves."),
    LIGHTNING_ROD("Lightning Rod", "Absorbs Electric-type moves."),
    STORM_DRAIN("Storm Drain", "Absorbs Water-type moves."),
    SAP_SIPPER("Sap Sipper", "Absorbs Grass-type moves."),
    MOTOR_DRIVE("Motor Drive", "Absorbs Electric-type moves and gains Speed."),
    THICK_FAT("Thick Fat", "Weakens Fire and Ice damage."),
    HEATPROOF("Heatproof", "Weakens Fire damage."),
    FILTER("Filter", "Reduces super-effective damage."),
    SOLID_ROCK("Solid Rock", "Reduces super-effective damage."),
    PRISM_ARMOR("Prism Armor", "Reduces super-effective damage."),
    MULTISCALE("Multiscale", "Halves damage at full HP."),
    SHADOW_SHIELD("Shadow Shield", "Halves damage at full HP."),
    WONDER_GUARD("Wonder Guard", "Only super-effective moves can hit."),
    STURDY("Sturdy", "Survives a hit from full HP."),
    MAGIC_GUARD("Magic Guard", "Only direct attacks deal damage."),
    NATURAL_CURE("Natural Cure", "Cures status on switch-out."),
    REGENERATOR("Regenerator", "Heals on switch-out."),
    POISON_HEAL("Poison Heal", "Heals instead of taking poison damage."),
    IMMUNITY("Immunity", "Prevents poison."),
    WATER_VEIL("Water Veil", "Prevents burn."),
    MAGMA_ARMOR("Magma Armor", "Prevents freeze."),
    LIMBER("Limber", "Prevents paralysis."),
    INSOMNIA("Insomnia", "Prevents sleep."),
    VITAL_SPIRIT("Vital Spirit", "Prevents sleep."),
    OWN_TEMPO("Own Tempo", "Prevents confusion."),
    OBLIVIOUS("Oblivious", "Prevents certain mental effects."),

    DRIZZLE("Drizzle", "Summons rain."),
    DROUGHT("Drought", "Summons sun."),
    SAND_STREAM("Sand Stream", "Summons sandstorm."),
    SNOW_WARNING("Snow Warning", "Summons hail."),
    ELECTRIC_SURGE("Electric Surge", "Creates Electric Terrain."),
    PSYCHIC_SURGE("Psychic Surge", "Creates Psychic Terrain."),
    GRASSY_SURGE("Grassy Surge", "Creates Grassy Terrain."),
    MISTY_SURGE("Misty Surge", "Creates Misty Terrain."),
    CLOUD_NINE("Cloud Nine", "Negates weather effects."),
    AIR_LOCK("Air Lock", "Negates weather effects."),
    RAIN_DISH("Rain Dish", "Heals in rain."),
    ICE_BODY("Ice Body", "Heals in hail."),
    DRY_SKIN("Dry Skin", "Heals in rain and from Water; hates sun and Fire."),
    HYDRATION("Hydration", "Cures status in rain."),
    LEAF_GUARD("Leaf Guard", "Prevents status in sun."),
    GRASSY_PELT("Grassy Pelt", "Boosts Defense in Grassy Terrain."),
    HADRON_ENGINE("Hadron Engine", "Boosts Sp. Atk in Electric Terrain."),
    ORICHALCUM_PULSE("Orichalcum Pulse", "Summons sun and boosts Attack."),
    PROTOSYNTHESIS("Protosynthesis", "Ancient power boost in sun."),
    QUARK_DRIVE("Quark Drive", "Future power boost in Electric Terrain."),

    SPEED_BOOST("Speed Boost", "Raises Speed each turn."),
    UNBURDEN("Unburden", "Doubles Speed after item loss."),
    PRANKSTER("Prankster", "Raises priority of status moves."),
    GALE_WINGS("Gale Wings", "Raises priority of Flying moves at full HP."),
    TRIAGE("Triage", "Raises priority of healing moves."),
    TRUANT("Truant", "Can only act every other turn."),
    SLOW_START("Slow Start", "Halves Attack and Speed early on."),
    STALL("Stall", "Usually moves last."),

    TRACE("Trace", "Copies an opponent's ability."),
    PRESSURE("Pressure", "Increases PP usage."),
    DOWNLOAD("Download", "Raises Attack or Sp. Atk on entry."),
    SERENE_GRACE("Serene Grace", "Boosts secondary effect chances."),
    SYNCHRONIZE("Synchronize", "Passes certain status back."),
    STATIC("Static", "May paralyze on contact."),
    FLAME_BODY("Flame Body", "May burn on contact."),
    POISON_POINT("Poison Point", "May poison on contact."),
    ROUGH_SKIN("Rough Skin", "Damages contact attackers."),
    IRON_BARBS("Iron Barbs", "Damages contact attackers."),
    EFFECT_SPORE("Effect Spore", "May inflict status on contact."),
    STEADFAST("Steadfast", "Raises Speed when flinched."),
    INNER_FOCUS("Inner Focus", "Prevents flinching."),
    CLEAR_BODY("Clear Body", "Prevents stat drops."),
    WHITE_SMOKE("White Smoke", "Prevents stat drops."),
    FULL_METAL_BODY("Full Metal Body", "Prevents stat drops."),
    SOUNDPROOF("Soundproof", "Immune to sound-based moves."),
    ARENA_TRAP("Arena Trap", "Prevents grounded foes from switching."),
    SHADOW_TAG("Shadow Tag", "Prevents foes from switching."),
    MAGNET_PULL("Magnet Pull", "Prevents Steel-types from switching."),
    NO_GUARD("No Guard", "All moves used by or against this Pokemon hit."),
    COMPOUND_EYES("Compound Eyes", "Raises move accuracy."),
    IMPOSTER("Imposter", "Transforms on entry in simplified form."),
    ILLUSION("Illusion", "Flavor-only in this simulator."),
    UNNERVE("Unnerve", "Prevents berry use in simplified form."),
    HARVEST("Harvest", "May restore berries in simplified form."),
    GLUTTONY("Gluttony", "Eats berries early in simplified form."),
    RIVALRY("Rivalry", "Flavor-only in this simulator."),
    KEEN_EYE("Keen Eye", "Prevents accuracy loss."),
    SCRAPPY("Scrappy", "Lets Normal and Fighting moves hit Ghosts."),
    INFILTRATOR("Infiltrator", "Bypasses substitutes and screens."),
    TINTED_LENS("Tinted Lens", "Boosts not very effective moves."),
    ANALYTIC("Analytic", "Boosts moves when moving last."),
    JUSTIFIED("Justified", "Raises Attack when hit by a Dark move."),
    MOXIE("Moxie", "Raises Attack after a KO."),
    BEAST_BOOST("Beast Boost", "Raises the highest stat after a KO."),
    SKILL_LINK("Skill Link", "Multi-hit moves strike 5 times."),
    POISON_TOUCH("Poison Touch", "Contact moves may poison."),

    COMPETITIVE("Competitive", "Raises Sp. Atk when stats drop."),
    DEFIANT("Defiant", "Raises Attack when stats drop."),
    CONTRARY("Contrary", "Reverses stat changes."),
    SIMPLE("Simple", "Doubles stat stage changes."),
    MOODY("Moody", "Raises one stat and lowers another each turn."),
    ANGER_POINT("Anger Point", "Maxes Attack after a critical hit."),
    ANGER_SHELL("Anger Shell", "Stat shift at low HP."),
    RATTLED("Rattled", "Raises Speed after certain move types."),
    STAMINA("Stamina", "Raises Defense when hit."),
    WEAK_ARMOR("Weak Armor", "Lowers Defense and raises Speed when hit."),
    STEAM_ENGINE("Steam Engine", "Sharply raises Speed when hit by Fire or Water."),
    INTREPID_SWORD("Intrepid Sword", "Raises Attack on entry."),
    DAUNTLESS_SHIELD("Dauntless Shield", "Raises Defense on entry."),
    SUPREME_OVERLORD("Supreme Overlord", "Boosts damage for fainted allies."),
    COSTAR("Costar", "Copies ally stat changes on switch-in."),

    PROTEAN("Protean", "Changes type to the move used."),
    LIBERO("Libero", "Changes type to the move used."),
    AERILATE("Aerilate", "Turns Normal moves into Flying moves."),
    REFRIGERATE("Refrigerate", "Turns Normal moves into Ice moves."),
    PIXILATE("Pixilate", "Turns Normal moves into Fairy moves."),
    GALVANIZE("Galvanize", "Turns Normal moves into Electric moves."),
    NORMALIZE("Normalize", "Turns moves into Normal type."),
    PUNK_ROCK("Punk Rock", "Boosts sound moves and resists them."),
    LIQUID_VOICE("Liquid Voice", "Turns sound moves into Water moves."),
    STEELY_SPIRIT("Steely Spirit", "Boosts Steel moves."),
    COLOR_CHANGE("Color Change", "Changes type when hit."),
    MIMICRY("Mimicry", "Changes type with terrain."),

    MAGIC_BOUNCE("Magic Bounce", "Reflects status moves."),
    UNAWARE("Unaware", "Ignores foe stat boosts."),
    FUR_COAT("Fur Coat", "Halves physical damage."),
    ICE_SCALES("Ice Scales", "Halves special damage."),
    FLUFFY("Fluffy", "Halves contact damage but weak to Fire."),
    WATER_BUBBLE("Water Bubble", "Boosts Water moves and weakens Fire."),
    BULLETPROOF("Bulletproof", "Immune to ball and bomb moves."),
    DAZZLING("Dazzling", "Blocks opposing priority."),
    QUEENLY_MAJESTY("Queenly Majesty", "Blocks opposing priority."),
    ARMOR_TAIL("Armor Tail", "Blocks opposing priority."),
    DISGUISE("Disguise", "Avoids one damaging hit."),
    NEUTRALIZING_GAS("Neutralizing Gas", "Suppresses abilities in simplified form."),
    OVERCOAT("Overcoat", "Immune to powder and weather damage."),
    MIRROR_ARMOR("Mirror Armor", "Reflects stat drops."),
    WONDER_SKIN("Wonder Skin", "Makes status moves less accurate."),
    GUARD_DOG("Guard Dog", "Prevents Intimidate and forced switching."),
    GOOD_AS_GOLD("Good as Gold", "Blocks status moves."),
    PURIFYING_SALT("Purifying Salt", "Reduces Ghost damage and blocks status."),
    WELL_BAKED_BODY("Well-Baked Body", "Immune to Fire and raises Defense."),
    WIND_RIDER("Wind Rider", "Immune to wind and raises Attack."),
    EARTH_EATER("Earth Eater", "Immune to Ground and heals."),
    VESSEL_OF_RUIN("Vessel of Ruin", "Lowers other active Pokemon Sp. Atk."),
    SWORD_OF_RUIN("Sword of Ruin", "Lowers other active Pokemon Defense."),
    BEADS_OF_RUIN("Beads of Ruin", "Lowers other active Pokemon Sp. Def."),
    TABLETS_OF_RUIN("Tablets of Ruin", "Lowers other active Pokemon Attack."),

    MUMMY("Mummy", "Replaces the attacker's ability on contact."),
    CURSED_BODY("Cursed Body", "May disable a move in simplified form."),
    GOOEY("Gooey", "Lowers Speed on contact."),
    TANGLING_HAIR("Tangling Hair", "Lowers Speed on contact."),
    AFTERMATH("Aftermath", "Damages contact attackers after being KOed."),
    COTTON_DOWN("Cotton Down", "Lowers foes' Speed when hit."),
    LINGERING_AROMA("Lingering Aroma", "Replaces the attacker's ability on contact."),
    WANDERING_SPIRIT("Wandering Spirit", "Swaps abilities on contact."),
    PERISH_BODY("Perish Body", "Starts perish count on contact."),
    TOXIC_DEBRIS("Toxic Debris", "Sets Toxic Spikes when hit by contact."),

    SHED_SKIN("Shed Skin", "May heal status each turn."),
    EARLY_BIRD("Early Bird", "Wakes quickly."),
    BAD_DREAMS("Bad Dreams", "Damages sleeping foes."),
    HEALER("Healer", "May heal allies in simplified form."),
    COMATOSE("Comatose", "Always counts as asleep in simplified form."),
    PASTEL_VEIL("Pastel Veil", "Prevents poison."),
    CUTE_CHARM("Cute Charm", "May infatuate in flavor form."),

    STANCE_CHANGE("Stance Change", "Form-based, simplified."),
    ZEN_MODE("Zen Mode", "Form-based, simplified."),
    FORECAST("Forecast", "Form-based, simplified."),
    SCHOOLING("Schooling", "Form-based, simplified."),
    SHIELDS_DOWN("Shields Down", "Form-based, simplified."),
    POWER_CONSTRUCT("Power Construct", "Form-based, simplified."),
    BATTLE_BOND("Battle Bond", "Form-based, simplified."),
    HUNGER_SWITCH("Hunger Switch", "Form-based, simplified."),
    ICE_FACE("Ice Face", "Blocks one physical hit."),
    ZERO_TO_HERO("Zero to Hero", "Form-based, simplified."),
    COMMANDER("Commander", "Doubles-only, simplified."),
    GULP_MISSILE("Gulp Missile", "Form-based, simplified.");

    private final String displayName;
    private final String description;

    Ability(String displayName, String description) {
        this.displayName = displayName;
        this.description = description;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getDescription() {
        return description;
    }
}
